var myIdToken;
var myRefreshToken;
String displayName = "";
List<dynamic> allPodcasts = [];
List<dynamic> favePodcasts = [];
List<dynamic> myCreations = [];
List<dynamic> alllive = [];
String currlive = "";
String email = "";
int numCre = 0;
int numFav = 0;
String viewlive = "";
